openapi: 3.0.0
info:
  title: "computate-bancaire-vertx"
  version: 3.0.0
servers:
  - url: https://dev.computate.org:10680
paths:
components:
  securitySchemes:
    openIdConnect:
      type: openIdConnect
      openIdConnectUrl: https://sso.computate.org/auth/realms/COMPUTATE.ORG/.well-known/openid-configuration
  requestBodies:
    ErrorResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    ErrorResponse:
      required:
        - type
        - code
      properties:
        type:
          type: string
          enum:
            - ERROR
            - WARN
            - INVALID
            - FATAL
          description: >+
            <br>invalid - Request did not confirm to the specification and was
            unprocessed & rejected. Please fix the value and try again</br>       
            <br>warn - Request was partially processed.  E.g. some of the fields
            are missing in response to the system issues,  request was accepted
            successfully but will be processed asynchronously</br>                
            <br>error - The request was accepted but could not be processed
            successfully</br>            <br>fatal - There was an internal system
            error while processing the request. These are technical errors and
            will be resolved by Citi, and the consumer should retry after some
            time. Business errors will not be categorized as fatal </br>
        code:
          type: string
          description: Error code which qualifies the error. 
        details:
          type: string
          description: Human readable explanation specific to the occurrence of the problem. 
        location:
          type: string
          description: The name of the field that resulted in the error. 
        moreInfo:
          type: string
          description: URI to human readable documentation of the error. 
